import { createClient } from '@supabase/supabase-js';
import { describeFace } from './face.js';
import './style.css';
const $ = id => document.getElementById(id);
const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const configured = url && key && !url.includes('YOUR-PROJECT') && !key.includes('YOUR-');
let db;
try { if (configured) db = createClient(url,key); } catch { /* Show setup state below. */ }
let mode = 'register', stream, photo, busy = false, allowed = false, cameraGeneration = 0;
document.querySelector('#app').innerHTML = `
<main><section id="setup" class="notice" hidden><strong>Connect your registry</strong><p>Supabase setup required. See README.</p></section>
<section id="login" class="card" hidden><h2>Sign in</h2><form id="login-form"><label for="email">Email</label><input id="email" type="email" autocomplete="username" required><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required><button class="primary" id="sign-in">Sign in</button></form></section>
<section class="card workspace"><div class="tabs" role="group" aria-label="Choose action"><button id="register-tab" class="selected" aria-pressed="true">Register</button><button id="identify-tab" aria-pressed="false">Identify</button></div>
<div class="workspace-body"><form id="face-form"><div id="name-field"><label for="name">Name</label><input id="name" maxlength="100" autocomplete="off" required></div>
<div class="photo-area" id="photo-area"><div id="photo-empty">Camera preview</div><video id="video" playsinline muted autoplay hidden></video><canvas id="photo" hidden></canvas><button id="clear-photo" type="button" class="clear" hidden aria-label="Remove photo">✕</button></div>
<div class="photo-actions"><button id="camera" type="button" class="secondary">Open camera</button><button id="upload" type="button" class="secondary">Upload photo</button><input id="file" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" hidden></div>
<div id="camera-actions" class="photo-actions" hidden><button id="capture" type="button" class="primary">Take photo</button><button id="cancel-camera" type="button" class="secondary">Cancel</button></div>
<label class="consent"><input id="consent" type="checkbox" required><span>I have this person’s permission to process their face photo<span id="consent-extra"> and save a face reference</span>.</span></label><button id="submit" class="primary submit" disabled>Register</button></form>
<div id="result" role="status" aria-live="polite" tabindex="-1" hidden></div></div></section><button id="sign-out" class="text-button" hidden>Sign out</button><div id="status" role="status" aria-live="polite"></div></main>`;
function message(text,error=false) { $('status').textContent=text; $('status').className=error?'error':''; }
function update() {
  for (const id of ['camera','upload','name','consent','register-tab','identify-tab','clear-photo','capture','cancel-camera']) $(id).disabled=busy||!allowed;
  $('submit').disabled=busy||!allowed||!photo;
  $('sign-out').disabled=busy;
  $('submit').textContent=busy?'Working…':mode==='register'?'Register':'Identify';
}
function stopCamera() { cameraGeneration++; stream?.getTracks().forEach(t=>t.stop()); stream=null; $('video').srcObject=null; $('video').hidden=true; $('camera-actions').hidden=true; $('photo-empty').hidden=!!photo; }
function resetPhoto() { stopCamera(); photo=null; const c=$('photo'); c.getContext('2d').clearRect(0,0,c.width,c.height); c.hidden=true; $('clear-photo').hidden=true; $('photo-empty').hidden=false; $('file').value=''; $('result').hidden=true; update(); }
function setMode(next) { if(busy)return; mode=next; resetPhoto(); $('name-field').hidden=next!=='register'; $('name').required=next==='register'; $('consent').checked=false; $('consent-extra').hidden=next!=='register'; for(const tab of ['register','identify']) { $(tab+'-tab').classList.toggle('selected',tab===next); $(tab+'-tab').setAttribute('aria-pressed',String(tab===next)); } message(''); }
function draw(source,width,height) { if(!width||!height)throw new Error('Camera is still starting. Try again in a moment.'); const c=$('photo'), scale=Math.min(1,1280/Math.max(width,height)); c.width=Math.round(width*scale); c.height=Math.round(height*scale); c.getContext('2d').drawImage(source,0,0,c.width,c.height); photo=c; stopCamera(); c.hidden=false; $('photo-empty').hidden=true; $('clear-photo').hidden=false; $('result').hidden=true; update(); }
$('register-tab').onclick=()=>setMode('register'); $('identify-tab').onclick=()=>setMode('identify');
$('clear-photo').onclick=resetPhoto; $('cancel-camera').onclick=stopCamera;
$('camera').onclick=async()=>{ resetPhoto(); const generation=cameraGeneration; message(''); try { if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera requires HTTPS and browser permission. You can upload a photo instead.'); const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280}},audio:false}); if(generation!==cameraGeneration){ next.getTracks().forEach(t=>t.stop());return; } stream=next; $('video').srcObject=stream; $('video').hidden=false; $('photo-empty').hidden=true; $('camera-actions').hidden=false; await $('video').play(); }catch(error){stopCamera();message(error.name==='NotAllowedError'?'Camera permission was denied. Allow camera access or upload a photo.':error.message,true);} };
$('capture').onclick=()=>{try{draw($('video'),$('video').videoWidth,$('video').videoHeight);}catch(e){message(e.message,true);}};
$('upload').onclick=()=>$('file').click();
$('file').onchange=async()=>{const file=$('file').files[0]; if(!file)return; resetPhoto(); if(file.size>15*1024*1024){message('Choose an image smaller than 15 MB.',true);return;} busy=true;update(); const objectUrl=URL.createObjectURL(file);try{const img=new Image();img.src=objectUrl;await img.decode();draw(img,img.naturalWidth,img.naturalHeight);message('Photo ready.');}catch{message('This image could not be opened. Try a JPEG, PNG or WebP photo. For HEIC, export as JPEG first.',true);}finally{URL.revokeObjectURL(objectUrl);busy=false;update();}};
$('face-form').onsubmit=async event=>{event.preventDefault();if(busy||!photo||!allowed)return;busy=true;update();$('result').hidden=true;message('Reading the face… First use may take a few seconds.');try {const descriptor=await describeFace(photo);message('Checking your registry…');const {data,error}=await db.rpc('face_lookup',{p_descriptor:descriptor,p_name:mode==='register'?$('name').value.trim():null});if(error)throw error; const titles={registered:'Registration complete',already_registered:'User is registered',identified:'Person identified',not_found:'Product not found',ambiguous:'Please try another photo'};const details={registered:'Saved for future recognition.',already_registered:'This person is already registered. No new entry was created.',identified:'A matching registered person was found.',not_found:'This person is not in the registry.',ambiguous:'The match is too close to call. No new entry was created. Use a clearer photo.'}; if(!titles[data?.status])throw new Error('Unexpected response from the registry.');$('result').replaceChildren();const title=document.createElement('h3');title.textContent=titles[data.status];const name=document.createElement('strong');name.textContent=data.name||'';const detail=document.createElement('p');detail.textContent=details[data.status];$('result').append(title,name,detail);$('result').className=['not_found','ambiguous'].includes(data.status)?'warning':'success';$('result').hidden=false;$('result').focus();message('');}catch(e){message(e.message||'Unable to contact the registry. Please try again.',true);}finally{busy=false;update();}};
$('login-form').onsubmit=async event=>{event.preventDefault();$('sign-in').disabled=true;message('Signing in…');const {error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('password').value='';$('sign-in').disabled=false;if(error)message(error.message,true);};
$('sign-out').onclick=async()=>{if(busy)return;const {error}=await db.auth.signOut();if(error)message(error.message,true);};
let authGeneration=0;
async function sessionChanged(session){const generation=++authGeneration;allowed=false;resetPhoto();$('login').hidden=!!session;$('sign-out').hidden=!session;if(session){const {data,error}=await db.rpc('face_operator_access');if(generation!==authGeneration)return;allowed=data===true&&!error;message(allowed?'':error?.message||'This account is not an approved operator. Ask the project owner to grant access.',!allowed);}else message('');update();}
if(!db){$('setup').hidden=false;update();}else{db.auth.onAuthStateChange((event,session)=>{if(['INITIAL_SESSION','SIGNED_IN','SIGNED_OUT','USER_UPDATED'].includes(event))setTimeout(()=>sessionChanged(session),0);});}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();});window.addEventListener('pagehide',stopCamera);
